[[Map]]
	name = "Map001"
	ele0 = "flower1"
	ele1 = "tttt002"
	data = """
ele0**-1*@@**,ele0**-1***,ele0*ele1:sor*-1***,ele0**-1***,ele0**-1***,ele0**-1***,ele0**-1***,ele0*ele1:def*-1***$
ele0**-1***,ele0**-1***,ele0*ele1:sor*-1***,ele0**-1***,ele0**-1***,ele0**-1***,ele0**-1***,ele0**-1***$
ele0**-1***,ele0*ele1:sor*-1***,ele0*ele1:sor*-1***,ele0**-1***,ele0**-1***,ele0**-1***,ele0**-1***,ele0**-1***$
ele0**-1***,ele0**-1***,ele0**-1***,ele0**-1***,ele0**-1***,ele0**-1***,ele0**Ilk0:東:敵***,ele0**-1***$
ele0**-1***,ele0**-1***,ele0**-1***,ele0**-1***,ele0**-1***,ele0**-1***,ele0**-1***,ele0**-1***$
ele0**-1***,ele0**-1***,ele0**-1***,ele0**-1***,ele0**Ilk1:東:敵***,ele0**-1***,ele0**-1***,ele0**-1***$
ele0**-1***,ele0**-1***,ele0**Ilk2:東:敵***,ele0**-1***,ele0**-1***,ele0**-1***,ele0**-1***,ele0**-1***$
ele0*ele1:def*-1***,ele0**-1***,ele0**-1***,ele0**-1***,ele0**-1***,ele0**-1***,ele0**-1***,ele0*ele1:def*-1***$
	"""
