[[Map]]
	name = "Map001"
	ele0 = "flower1"
	ele1 = "obj_brickwall (1)"
	data = """
ele0**-1*@@**,ele0**-1***,ele0*ele1:def*-1***ele0**-1*@**,ele0**aaaa,北,敵***,ele0**-1***ele0**-1***,ele0**-1***,ele0**-1***	"""
