[[Process]]
	map = "map001.toml,map002.toml,map003.toml"
	map001.toml = "IlkayWarrior*10,kenshi*10,IlkaySpellcaster*10"
	map002.toml = "IlkayWarrior*20,kenshi*20,IlkaySpellcaster*20"
	map003.toml = "IlkayWarrior*30,kenshi*30,IlkaySpellcaster*30"
