[[Process]]
	map = "map001.toml,map002.toml,map003.toml"
	map001.toml = "IlkayWarrior*1,kenshi*1,IlkaySpellcaster*1"
	map002.toml = "LineInfantryM14*5,LineInfantryM14*5,LineInfantryM14*5"
	map003.toml = "LineInfantryM14*6,LineInfantryM14*6,LineInfantryM14*6"
