[[Skill]]
	name_tag = "gunLaphroaig"
	#スキルをグループ化します。上位スキルによる上書き判定に使えます。
	#同名文字列なら同系統のスキルと見なされ、大きい数値のスキルが低い数値を上書きします。
	fkey = "gun*1"

	#省略時は0。ユニットのスキルの並び順を決めます。小さい数値ほど前になります。
	#スキル発動優先順位がこれ
	sortkey = "1"

	#func=文字列でスキルタイプを指定する。能力低下スキルは遠距離／攻撃魔法からのnextスキルでのみ有効。
	func = "missile"

	# 複数指定で重ねる
	icon = "f_attack.png, _num5.png, _num1.png, we_gun010.png"

	#スキルの名称
	name = "【ニードルガン・ラフロイグ式lv1】"

	#説明文
	help = """
		さすがは帝国と言わざるを得ない、先進的ボルトアクション小銃$
		アレクサンド歴1850年時点での銃と言えば、前装式滑腔式歩兵銃のことだが、$
		帝国は既にこのような画期的兵器を作り出していた。$
		しかしその価値を理解していたのは少数の人間で、$
		多くの、例えば第一方面軍司令部ですら、$
		帝国が戦場で優位に立っていた理由を誤解している。$
		その為、「よくわからん」という理由で東アイディオール株式会社のような、$
		試験的あるいは犠牲的存在に多く回されている。幸か不幸か──。
		"""

	#省略時はoffです。スキルの発生座標を調整します。これはなるべくonにしてください。
	#on	スキル画像の中心を術者の中心に合わせた位置で出現させる
	#off	スキル画像の底辺を術者の底辺に合わせた位置で出現させる
	#end	スキル画像の末端を術者の中心に合わせた位置で出現させる
	#静止型スキルでcenter=endとd360=onを併せて使う事で術者から伸びる槍を表現できます。
	center = "on"

	#消費MP。mp≠0で攻撃魔法となる。mp＝0で遠距離攻撃になる。
	#負の値にするとmpが増えます。
	mp = "0"

	#省略時は75%。発射した時の移動速度変化率。
	#減速無しにする時はslow_per=100とします。
	#停止にする時はslow_per=-1としてください（0だと未指定扱いで75%と同義と見なされる）
	slow_per = "100"

	#省略時は1です。発射後に数値分の攻撃間隔だけ減速され続けます。
	#speed=60のユニットでslow_time=1とすると約二秒間減速状態が続きます。
	#減速時間無しにする時は-1とします（0だと未指定扱いで1と同義と見なされる）
	slow_time = "-1"

	#効果音。soundフォルダのwavファイルを拡張子無しで指定。複数列挙するとランダムでどれかが再生される。
	sound = "gun19, gun21, gun30"

	#画像設定
	image = "a_bullet"

	#(on/roll/off)
	#rollにすると360度回転します（d360=onと同じです）
	#onにするとスキルの進行方向によって画像が変化する。d360より描画処理が軽いのが存在理由です。
	#image = arrow
	#direct = on
	#とすると上下左右にはarrowNを、斜めにはarrowNWを向きに応じて反転表示する。
	#末尾にNとNWが付加された画像を用意してください。
	direct = "on"
	
	#(横サイズ)
	w = "12"
	
	#(縦サイズ)
	h = "12"

	# (透明度)
	a = "200"

	#offで「味方遮蔽」スキルとなります。
	#省略時は直進型と回転型で「味方遮蔽」になります。
	#「味方遮蔽」とは異なる部隊の味方ユニットが前方にいると発射不可となる事です。
	force_fire = "on"

	#スキルの属性
	attr = "taiho"

	#数値は百分率の係数。50なら50%となる。0にするとゼロダメージとなるが状態異常は付加される。
	str = "attack_dext * 120"
	
	#射程距離。
	range = "750"

	#ダメージ減衰距離。省略時は0となり0だと減衰しません。
	damage_range_adjust = "0"

	#0以外に指定するとこの距離以内なら発射しなくなります。
	range_min = "145"

	#省略するとspeed=0となり静止型スキルとなります。movetypeによって意味が異なります。
	#speed = 100で、1フレームに約1ドット進む。（ベクトルを使用している為、厳密に1ドット進むというのが難しい
	speed = "4500"
	
	#*数値と指定すると、その回数分、使えなくなる
	#*2だと二回分同じグループのスキルが使えない
	gun_delay = "gunLaphroaig*1"

	#発射と同時に発生する別スキル。スキル発射時のエフェクトとして使用する。
	#術者が最初に発射するskillのみ有効です。
	#pair_nextは簡易戦闘時に発生しないので実戦闘との整合性を取る為に必ず攻撃力の無いスキルを指定してください。
	pair_next  = "b_kemuri_eff02"

	#敵にヒット時に発生させる次のスキル。
	next = "m_hit_eff01"

	#数値ﾄﾞｯﾄ半径内のランダム位置に着弾します。
	#0を指定するとほぼ当たらないので、銃の場合は5や10などの数値を指定することをお勧めします。
	random_space = "10"

	#相殺できる属性と武器属性を列挙する。
	offset = "on"

	#４つの色成分をそれぞれ（0〜255）で指定する。プレイヤーユニット発射時に射線が表示される。
	ray = "185, 255, 255, 255"
	
	#rayの太さを指定
	ray_strokeThickness = "3"

	#onにすると射線が表示される。
	force_ray = "on"

	#連射数
	#未定義は-1
	rush = "-1"
	
	#連射間隔。省略時は0。ここでは0は5と同義と見なされるので実質5です。
	#同時に発射させたい時はrush_interval = -1 としてください。
	rush_interval = "-1"

	#指定角度範囲内でランダム方向に発射。
	#未定義は-1
	rush_random_degree = "-1"
