[[TestBattle]]
	name = "ca"
	#battle mao
	map = "map1"
	#Sortie unit
	memberKougeki = "ghostFireTest,ghostFireTest,ghostFireTest,ghostFireTest,ghostFireTest"
	#Def unit
	memberBouei = "AbelIrijhorn,VictodyRoyle,JothianRoarcy,MabateRoarcy,LineInfantryM14*5,LineInfantryM14*4,LineInfantryM14*3,DragoonFrancesca*7"
	#player
	player = "Def"
[[TestBattle]]
	name = "cb"
	#battle mao
	map = "map1"
	#Sortie unit
	memberKougeki = "ghostFireTest,ghostFireTest,ghostFireTest,ghostFireTest,ghostFireTest"
	#Def unit
	memberBouei = "AbelIrijhorn,VictodyRoyle,JothianRoarcy,MabateRoarcy,LineInfantryM14*5"
	#player
	player = "Def"