[config]
	DistanceBetweenUnit = 32
	DistanceBetweenUnitTate = 32
	TitleMenuX = 50
	TitleMenuY = 40
	TitleMenuSpace = 32
	strategyMenu000 = true
	strategyMenu001 = true
	strategyMenu002 = true
	strategyMenu003 = true
	strategyMenu004 = true
	strategyMenu005 = true
	strategyMenu006 = true
	strategyMenu007 = true
	strategyMenu008 = true
	strategyMenu009 = true
