[[SystemString]]
	lang = "en"
	configSave = "save"
	configLoad = "load"
	selectScenario = "scenario"
	selectScenario2 = "other"
	selectChara1 = "Please select a character to play"
	DoYouWantToQuitTheGame = "Do you want to quit the game"
	strategyMenu000 = "Plus unit."
	strategyMenu001 = "Training."
	strategyMenu002 = "Get skill."
	strategyMenu003 = "Facility."
	strategyMenu004 = "Politics."
	strategyMenu005 = "Bonus."
	strategyMenu006 = "Supply."
	strategyMenu007 = "Save."
	strategyMenu008 = "Load."
	strategyMenu009 = "Battle."
	BattleMessage001 = "Shall we dance?"
