[[Map]]
	name = "Map001"
	ele0 = "doro1"
	ele1 = "testWall_bu"
	ele2 = "testWall_buu"
	data = """
ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,@,
ele0**-1**,ele0**-1*@@**,ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,@,
ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,@,
ele0*ele2:sor*-1**,ele0*ele2:sor*-1**,ele0*ele2:sor*-1**,ele0*ele1:sor*-1**,ele0*ele1:sor*-1**,ele0*ele1:sor*-1**,ele0**-1**,ele0**-1**,@,
ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,@,
ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,@,
ele0**-1**,ele0**-1*@**,ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,@,
ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,ele0**-1**,@,
	"""
